import './expansion-workbench.js';
import './integrated-modules.css';
import {renderMaterialTables,materialCsvRows} from './steel-material-view.js';
import {projectPart,projectRequest,clone} from './project-store-client.js';
import {fingerprint} from './expansion-core.js';
import {PROJECT} from './intake-core.js';
import {DECISION_CONDITIONS,regionalInputs} from './regional-decision-guide.js';
import {RESEARCH_VERSION,RESEARCH_METHOD,researchDraft} from './decision-research-method.js';
import {DECISION_TOPICS,DECISION_GROUPS,decisionGuide,decisionSignature,currentDecisions,confirmDecision,materialSummary,steelSignature,convertCleaningBundle} from './module-integration-core.js';

const W=window.WorkbenchProjects,L=window.WorkbenchLegacy,I=window.WorkbenchIntake,E=window.ExpansionWorkbench;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=2)=>n===null||n===undefined||!Number.isFinite(n)?'—':n.toLocaleString('zh-CN',{maximumFractionDigits:d});
const uuid=()=>crypto.randomUUID();
const fresh=()=>({schema:1,decisions:[],steel:{units:{}},regulation:{runs:[]},history:[]});
let state=fresh(),store,loading=true,busy=false,saveTimer,activeUnit=PROJECT,activeDecisionGroup='seismic',activeDecisionTopic='intensity',expansions={},frame=null,frameReady=false,lastOutputVersion='',portfolio=[],bundlePreview=null;
const panel=(id,title)=>{const el=document.createElement('section');el.className='im-panel';el.id=id;el.innerHTML='<h2>'+title+'</h2>';return el;};
function addStage(n,tab,name,desc){const el=document.createElement('section');el.id='stage'+n;el.hidden=true;document.querySelector('#stage9').after(el);const b=document.createElement('button');b.id='tab'+n;b.textContent=tab;b.onclick=()=>L.go(n);document.querySelector('#tab9').parentElement.append(b);L.registerCard({id:'c'+n,n,tab,name,sec:el.id,stage:['扩初','施工图'],roles:{d:'填',m:'审',a:'看'},desc});return el;}
const decisionPanel=panel('im-decisions','重难点判断 · 项目决定');
addStage(10,'⑩ 重难点判断','抗震、绿色装配式与性能化目标','读取已确认资料，保留判断依据；负责人确认后供统一措施、扩初和PPT引用。').append(decisionPanel);
const pptPanel=panel('im-ppt','汇报 PPT · 当前项目成果');
addStage(11,'⑪ 汇报 PPT','扩初汇报 PPT','读取项目及单体参数、确认的重难点和模型结果；沿用已有16页模板、图片管理与PPT输出。').append(pptPanel);
document.querySelector('[onclick="wbOpenPptReport()"]')?.setAttribute('hidden','');
const steelPanel=panel('im-steel','用钢量');document.querySelector('#stage5').prepend(steelPanel);
// Keep parser-bound DOM nodes inert; the legacy tools have no visible entry.
const legacySteel=document.createElement('div');legacySteel.hidden=true;legacySteel.inert=true;for(const el of [...document.querySelector('#stage5').children])if(el!==steelPanel)legacySteel.append(el);document.querySelector('#stage5').append(legacySteel);
const overviewPanel=panel('im-overview','项目管理总览 · 已审核用量');document.querySelector('#stage6').prepend(overviewPanel);
const oldOverview=document.createElement('details');oldOverview.className='im-panel';oldOverview.innerHTML='<summary>旧版项目快照与导出工具</summary>';for(const el of [...document.querySelector('#stage6').children])if(el!==overviewPanel)oldOverview.append(el);document.querySelector('#stage6').append(oldOverview);
const cleaningPanel=panel('im-cleaning','接入已有资料清洗成果');document.querySelector('#intake-panel').after(cleaningPanel);
const dialog=document.createElement('dialog');dialog.className='im-dialog';document.body.append(dialog);
const noteEl=document.createElement('p');noteEl.id='im-status';noteEl.setAttribute('role','status');document.querySelector('.wp-bar').append(noteEl);
const note=s=>noteEl.textContent=s;
function researchPanel(){
  const report=state.research?.[activeUnit];if(!report)return '';
  const item=report.items.find(x=>x.topic===activeDecisionTopic);if(!item)return '';
  const stale=report.inputSignature!==decisionSignature(contextFor(activeUnit))||report.methodVersion!==RESEARCH_VERSION;
  const citations=item.citations.map(c=>{const s=report.sources.find(s=>s.source_id===c.source_id);return '<p><b>'+esc(s?.title)+'</b> · '+esc(c.locator)+'<br>'+esc(c.quote)+'<br>'+(/^https:\/\//.test(s?.url||'')?'<a target="_blank" rel="noopener" href="'+esc(s.url)+'">官方来源</a>':'')+' · '+esc(s?.kind)+' · '+esc(s?.retrievedAt)+'</p>';}).join('');
  return '<section class="im-panel"><h3>DeepSeek · '+esc(item.title)+' <small>'+(stale?'输入已变化，请重新研判':'AI草稿 · 待人工复核')+'</small></h3><p><b>'+esc(item.conclusion)+'</b></p><p>'+esc(item.conditions.join('；'))+'</p><p>'+esc([...item.missing,...report.warnings].join('；'))+'</p><details><summary>依据、落实要求与检索记录</summary>'+citations+'<p>'+esc(item.checks.join('；'))+'</p><p>'+esc(report.trace.map(t=>t.group+'：'+(t.error||`${t.count}个候选${t.cacheHit?'（复用缓存）':''}`)).join('；'))+'</p></details><button id="im-research-adopt" '+(stale||!item.citations.length||!canEdit('c10')?'disabled':'')+'>按AI草稿编制</button></section>';
}
function openResearch(){
  if(!canEdit('c10'))return note('当前状态不允许研判，请等待载入或先撤回签发');
  const location=I.parameters(activeUnit).region||'';
  dialog.innerHTML='<div class="im-panel"><h2>DeepSeek 地区研判</h2><p>地点：'+esc(location||'请先在①填写')+' · '+esc(activeUnit)+'</p><p>一次检索抗震、绿色与装配式、性能化三个方面。仅发送当前单体判断条件和规范目录，不发送原始文件；使用现有 DeepSeek 配置，联网搜索也会产生调用费用。</p><details><summary>内嵌检索方法</summary><ol>'+RESEARCH_METHOD.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></details><label><input type="checkbox" id="im-research-refresh"> 重新检索，不使用24小时内的来源缓存</label><div class="im-row"><button id="im-research-run" '+(!location?'disabled':'')+'>开始检索并研判</button><button id="im-research-close">关闭</button></div><p id="im-research-progress" role="status"></p></div>';
  dialog.querySelector('#im-research-close').onclick=()=>dialog.close();
  dialog.querySelector('#im-research-run').onclick=async()=>{
    const who=W.id,unit=activeUnit,context=contextFor(unit),inputSignature=decisionSignature(context),button=dialog.querySelector('#im-research-run'),progress=dialog.querySelector('#im-research-progress');
    const refresh=dialog.querySelector('#im-research-refresh').checked;busy=true;button.disabled=true;progress.textContent='正在检索官方来源并核对项目条件，通常需要1—3分钟…';
    try{const response=await fetch('/api/decision-research',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Request':'decision-research'},body:JSON.stringify({consent:true,refresh,context:{unit,parameters:context.parameters,facts:context.facts.map(({key,value,unit,status})=>({key,value,unit,status})),regulations:context.regulations.map(({title,code,status,review,source_id,source_url,selected})=>({title,code,status,review,source_id,source_url,selected}))}})});const report=await response.json();if(!response.ok)throw Error(report.error||'研判未完成');if(who!==W.id)throw Error('项目已切换，结果未写入其他项目');
      state.research||={};if(state.research[unit]){state.researchHistory||=[];state.researchHistory.push(state.research[unit]);state.researchHistory=state.researchHistory.slice(-4);}state.research[unit]={...report,inputSignature};await save();dialog.close();note('地区研判已保存为AI草稿；请选择专题查看，人工决定未覆盖');
    }catch(e){progress.textContent=e.message;note(e.message);}finally{busy=false;button.disabled=false;renderDecisions();}
  };dialog.showModal();
}
const units=()=>[PROJECT,...new Set([...I.units,...Object.keys(state.steel.units),...state.decisions.map(d=>d.unit)].filter(n=>n&&n!==PROJECT))];
const options=(list,chosen)=>list.map(n=>'<option '+(n===chosen?'selected':'')+'>'+esc(n)+'</option>').join('');
const unitPicker=id=>'<label>适用单体 <select id="'+id+'">'+options(units(),activeUnit)+'</select></label>';
function canEdit(id){return !!store&&!loading&&!busy&&!W.loading&&L.canEdit(id);}
function requireEdit(id){if(!canEdit(id))throw Error('当前角色、阶段或签发状态不允许修改，请先撤回签发或切换角色');}
async function save(){clearTimeout(saveTimer);if(!loading&&store)await store.save(state);}
function schedule(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>save().catch(e=>note(e.message)),500);}
function emit(){window.dispatchEvent(new Event('workbuddy:decisions-changed'));publishPpt();}
async function action(run){if(busy||loading||W.loading)return;try{await run();await save();render();}catch(e){note(e.message);}finally{busy=false;}}
function record(event){state.history.push({event,at:new Date().toISOString(),by:L.role()});schedule();}
function modelState(unit){const current=E.capture();return current?.identity.unit===unit?current:expansions[unit];}
function contextFor(unit){const e=modelState(unit);return {unit,parameters:I.parameters(unit),facts:I.evidence(unit).facts,model:e?.model||null,regulations:(e?.regulations||[]).filter(r=>r.selected)};}
function accepted(unit){return currentDecisions(state.decisions,unit,contextFor);}
function decisionEvidence(unit){const records=accepted(unit);return {facts:records.map(r=>({id:'KD-'+r.id,key:'arch_decision_'+r.topic+'_'+r.id,label:DECISION_TOPICS.find(t=>t[0]===r.topic)?.[2]||'重难点',value:r.conclusion,unit:r.unit,status:'confirmed',statement:'我的观点（负责人确认）',source_id:'KD-'+r.id,filename:'重难点判断 · '+(r.source_title||'已确认判断'),locator:r.locator,quote:r.evidence,origin:'decisions'})),sources:records.map(r=>({source_id:'KD-'+r.id,name:'重难点判断',origin:'decisions',slot:'decision',fragments:[{text:r.evidence,locator:r.locator}],evidence:[r.source_id],reviewedAt:r.reviewedAt}))};}
function renderDecisions(){
  const rows=state.decisions.filter(r=>r.unit===activeUnit),group=DECISION_GROUPS.find(g=>g[0]===activeDecisionGroup)||DECISION_GROUPS[0],topicIds=group[3];
  if(!topicIds.includes(activeDecisionTopic))activeDecisionTopic=topicIds[0];
  const topicMeta=DECISION_TOPICS.find(t=>t[0]===activeDecisionTopic),context=contextFor(activeUnit),guide=decisionGuide(context,activeDecisionTopic),topicRows=rows.filter(r=>r.topic===activeDecisionTopic),current=topicRows.at(-1),stale=current?.status==='confirmed'&&current.signature!==decisionSignature(context),valid=current?.status==='confirmed'&&!stale;
  decisionPanel.classList.toggle('im-ai-only',!guide&&Boolean(state.research?.[activeUnit]));
  const input=guide?.input||{location:context.parameters?.region||'',use:'',structure:context.parameters?.struct_sys||'',height:null,floors:null,area:null,intensity:context.parameters?.intensity||'',pga:context.parameters?.pga||'',category:context.parameters?.seismic_cat||''};
  const conditions=[input.use,input.category,input.structure,input.height!==null?'高度'+input.height+'m':'',input.floors!==null?'地上'+input.floors+'层':'',input.area!==null?'面积'+input.area+'㎡':''].filter(Boolean).join(' · ')||'请从①确认单体用途、结构体系、高度等条件';
  const ruleRows=guide?guide.rows.map(r=>'<tr data-source-id="'+esc(r.source_id)+'"><td data-label="判断层级">'+esc(r.level)+'</td><td data-label="依据及版本"><b>'+esc(r.rule)+'</b>'+(/^https?:\/\//.test(r.url||'')?'<br><a href="'+esc(r.url)+'" target="_blank" rel="noopener">查看依据</a>':'')+(r.verification?'<br><small>'+esc(r.verification)+'</small>':'')+'</td><td data-label="判断结果"><strong>'+esc(r.result)+'</strong></td><td data-label="条文摘要／落实要求">'+esc(r.text)+'</td></tr>').join(''):'<tr><td data-label="判断层级">地方规则</td><td data-label="依据及版本">当前没有已校核的地区规则模板</td><td data-label="判断结果"><strong>待核查</strong></td><td data-label="条文摘要／落实要求">先在③查询并核对项目所在地的现行规定，再编制本专题判断。</td></tr>';
  const displayed=valid?current.conclusion:guide?.conclusion||current?.conclusion||'尚未形成判断',status=stale?'输入已变化 · 待复核':valid?'负责人已确认':current?.status==='draft'?'已有判断草稿':guide?.ready?'规则候选已就绪':'条件不全 · 仅供核对';
  const recordHtml=rows.length?rows.map(r=>{const oldStale=r.status==='confirmed'&&r.signature!==decisionSignature(contextFor(r.unit));return '<article class="im-decision-record"><b>'+esc(DECISION_TOPICS.find(t=>t[0]===r.topic)?.[2]||r.topic)+'</b><span class="im-badge">'+(oldStale?'输入已变化 · 待复核':r.status==='confirmed'?'负责人已确认':'判断草稿')+'</span><p>'+esc(r.conclusion)+'</p><details><summary>查看依据、条文定位和历次记录</summary><p>'+esc(r.scope)+'</p><pre>'+esc((r.source_title||'依据见条文摘录')+' · '+r.locator+'\n'+r.evidence)+'</pre><pre>'+esc(JSON.stringify((r.history||[]).map(({source_id,...h})=>h),null,2))+'</pre></details><button data-edit-decision="'+r.id+'" '+(!canEdit('c10')?'disabled':'')+'>编辑／复核</button></article>';}).join(''):'<p class="im-muted">本单体尚无判断记录。</p>';
  decisionPanel.innerHTML='<div class="im-decision-heading"><div><h2>重难点判断</h2><p>先查国家规则，再核对地方规定；正式结论须经专业负责人确认。</p></div><div class="im-decision-tools">'+unitPicker('im-decision-unit')+'<button data-go="1">统一措施</button><button id="im-condition-edit" '+(!I.busy&&L.canEditMeasures()?'':'disabled')+'>补充判断条件</button><button data-go="3">核查规范</button></div></div>'+
    '<div class="im-decision-groups">'+DECISION_GROUPS.map(([id,title,sub])=>'<button data-decision-group="'+id+'" class="'+(id===activeDecisionGroup?'active':'')+'"><b>'+title+'</b><span>'+sub+'</span></button>').join('')+'</div>'+
    '<div class="im-decision-params"><div><small>项目所在地</small><b>'+esc(input.location||'待确认')+'</b></div><div><small>项目条件</small><b>'+esc(conditions)+'</b></div><div><small>设防参数</small><b>'+esc([input.intensity&&input.intensity+'度',input.pga].filter(Boolean).join(' · ')||'待确认')+'</b></div></div>'+
    '<section class="im-decision-result"><div class="im-decision-title"><div><h3>'+esc(group[1])+'</h3><p>'+esc(group[1]==='抗震判断'?'抗震设防烈度与抗震等级合并判断。':group[1]==='绿色与装配式'?'绿色建筑等级与装配式要求分别判断。':'国标提出性能目标，地方规定落实适用条件。')+'</p></div><div class="im-decision-subtabs">'+topicIds.map(id=>'<button data-decision-topic="'+id+'" class="'+(id===activeDecisionTopic?'active':'')+'">'+esc(DECISION_TOPICS.find(t=>t[0]===id)?.[2])+'</button>').join('')+'</div></div>'+
    '<div class="im-scroll"><table class="im-decision-table"><thead><tr><th>判断层级</th><th>依据及版本</th><th>判断结果</th><th>条文摘要／落实要求</th></tr></thead><tbody>'+ruleRows+'</tbody></table></div>'+
    (guide?.steps?'<div class="im-decision-logic">'+guide.steps.map((s,i)=>'<div><small>'+esc((i+1)+' · '+s.label)+'</small><b>'+esc(s.value)+'</b><span>'+esc(s.result)+'</span></div>').join('')+'</div>':'')+
    ((guide?.missing?.length||guide?.warnings?.length)?'<p class="im-decision-missing">'+esc([...guide.missing,...guide.warnings].join('；'))+'</p>':'')+
    '<div class="im-decision-conclusion"><div><small>'+(valid?'已确认采用':'当前项目判断 · 待负责人复核')+'</small><strong>'+esc(displayed)+'</strong></div><p>'+esc(valid?'该结论已进入①②⑪；项目输入变化后自动转为待复核。':guide?.note||'当前地区尚无已校核规则模板。')+'</p></div>'+
    (guide?.actions?.length?'<details class="im-decision-followthrough"><summary>设计落实与待核资料</summary><ul>'+guide.actions.map(a=>'<li>'+esc(a)+'</li>').join('')+'</ul></details>':'')+
    '<div class="im-decision-actions"><span class="im-badge">'+esc(status)+'</span><button data-new-decision="'+activeDecisionTopic+'" '+(!canEdit('c10')?'disabled':'')+'>'+esc(current?'编辑／复核判断':guide?.ready?'按建议编制':'编制判断')+'</button></div></section>'+
    researchPanel()+'<details class="im-decision-records"><summary>本单体判断记录（'+rows.length+'）</summary>'+recordHtml+'</details>'+
    '<details class="im-decision-records"><summary>参考原型</summary><p>仅用于查看历史页面，不作为当前项目事实。</p><a target="_blank" rel="noopener" href="./design/key-decisions/key-decisions-baoshan-prototype.html">保山判断原型</a></details>';
  decisionPanel.querySelector('#im-condition-edit').onclick=editDecisionConditions;
  const researchButton=document.createElement('button');researchButton.textContent='DeepSeek 地区研判';researchButton.disabled=!canEdit('c10');researchButton.onclick=openResearch;decisionPanel.querySelector('.im-decision-tools').append(researchButton);
  const adopt=decisionPanel.querySelector('#im-research-adopt');if(adopt)adopt.onclick=()=>{const report=state.research[activeUnit];if(report.inputSignature!==decisionSignature(contextFor(activeUnit)))return note('输入已变化，请重新研判');editDecision(activeDecisionTopic,null,{...researchDraft(report,activeDecisionTopic),research_signature:report.inputSignature});};
  decisionPanel.querySelector('#im-decision-unit').onchange=e=>{activeUnit=e.target.value;render();};
}
function editDecisionConditions(){
  if(!L.canEditMeasures()||I.busy)return;
  const unit=activeUnit,input=regionalInputs(contextFor(unit)),who=W.id;
  dialog.innerHTML='<div class="im-panel"><h2>判断条件 · '+esc(unit)+'</h2><p>地点、烈度和体系沿用①；以下补充条件保存到同一项目资料与统一措施采用记录。</p><div class="im-grid">'+DECISION_CONDITIONS.map(([key,label,choices])=>'<label>'+esc(label)+(Array.isArray(choices)?'<select data-condition="'+key+'"><option value="">待确认</option>'+choices.map(v=>'<option '+(input[key]===v?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select>':'<input type="date" data-condition="'+key+'" value="'+esc(input[key])+'">')+'</label>').join('')+'</div><p>请依据当前项目资料确认；清空字段会撤回该项采用值。2023年通知的许可适用性需对照规划许可及过渡条款。</p><button id="im-condition-save">确认条件并联动</button> <button id="im-condition-close">取消</button><p id="im-condition-status" role="status"></p></div>';
  dialog.querySelector('#im-condition-close').onclick=()=>dialog.close();
  dialog.querySelector('#im-condition-save').onclick=async()=>{
    const button=dialog.querySelector('#im-condition-save');button.disabled=true;
    try{if(who!==W.id)throw Error('项目已切换');const values=Object.fromEntries([...dialog.querySelectorAll('[data-condition]')].map(e=>[e.dataset.condition,e.value]));const ok=await I.confirmDecisionConditions(unit,values);if(!ok)throw Error('条件未保存，请查看资料区提示');dialog.close();render();note('已保存到统一措施采用记录，判断已重新计算');}
    catch(e){dialog.querySelector('#im-condition-status').textContent=e.message;}finally{button.disabled=false;}
  };dialog.showModal();
}
function editDecision(topic,old,suggested){
  requireEdit('c10');const openingSignature=decisionSignature(contextFor(activeUnit)),r=old||{id:uuid(),topic,unit:activeUnit,...(suggested||{})};
  const proposal=decisionGuide(contextFor(r.unit),r.topic)?.draft,needsRecheck=old?.status==='confirmed'&&old.signature!==openingSignature;let refreshed=false;
  dialog.innerHTML='<div class="im-panel"><h2>'+esc(DECISION_TOPICS.find(t=>t[0]===r.topic)?.[2])+' · '+esc(r.unit)+'</h2><p>复用当前单体参数。判断不会直接改写统一措施的工程参数；确认后进入成果依据。</p><label>判断结论<textarea id="kd-result">'+esc(r.conclusion)+'</textarea></label><label>适用条件与范围<input id="kd-scope" value="'+esc(r.scope||r.unit)+'"></label><label>依据规范或资料<input id="kd-source-title" value="'+esc(r.source_title||'')+'" placeholder="例如：规范全称、图纸名称或审查意见"></label><label>原文定位<input id="kd-locator" value="'+esc(r.locator)+'" placeholder="版本、条文号、图号或页码"></label><label>原文摘录与判断理由<textarea id="kd-evidence">'+esc(r.evidence)+'</textarea></label><p>陈述类型：我的观点；确认人、输入版本和内部审计标识由系统保存。</p><div class="im-row"><button id="kd-draft">保存草稿</button><button id="kd-confirm" '+(L.role()!=='m'?'disabled':'')+'>负责人确认并联动</button><button id="kd-close">关闭</button></div><p id="kd-status" role="status"></p></div>';
  dialog.querySelector('#kd-close').onclick=()=>dialog.close();
  if(needsRecheck&&proposal){const box=document.createElement('div');box.className='im-decision-missing';box.innerHTML='<p>输入已变化。原文保留在编辑框中；当前建议：'+esc(proposal.conclusion)+'</p><button type="button">采用当前建议</button>';dialog.querySelector('#kd-result').parentElement.before(box);box.querySelector('button').onclick=()=>{for(const [id,key] of [['kd-result','conclusion'],['kd-scope','scope'],['kd-source-title','source_title'],['kd-locator','locator'],['kd-evidence','evidence']])dialog.querySelector('#'+id).value=proposal[key]||'';r.rule_version=proposal.rule_version;refreshed=true;box.querySelector('p').textContent='已载入当前建议，请复核后确认。';};}
  const commit=async confirm=>{try{requireEdit('c10');const value=id=>dialog.querySelector(id).value.trim(),sourceTitle=value('#kd-source-title');let next={...r,conclusion:value('#kd-result'),scope:value('#kd-scope'),source_title:sourceTitle,source_id:r.source_id||'KD-MANUAL-'+fingerprint([r.unit,r.topic,sourceTitle]),locator:value('#kd-locator'),evidence:value('#kd-evidence'),status:'draft',history:[...(r.history||[]),...(old?[{conclusion:r.conclusion,status:r.status,source_title:r.source_title,signature:r.signature,at:new Date().toISOString()}]:[])]};if(!next.conclusion)throw Error('请填写判断结论');if(!next.source_title)throw Error('请填写依据规范或资料');if(confirm){if(r.ai_research_version&&(r.ai_research_version!==RESEARCH_VERSION||r.research_signature!==decisionSignature(contextFor(r.unit))))throw Error('AI草稿依据的输入已变化，请重新研判再编制');if(needsRecheck&&proposal&&!refreshed&&next.conclusion===old.conclusion)throw Error('输入已变化，请采用当前建议或修订结论后再确认');if(openingSignature!==decisionSignature(contextFor(r.unit)))throw Error('输入已变化，请关闭后重新编制判断');if(r.rule_version&&!decisionGuide(contextFor(r.unit),r.topic)?.ready)throw Error('请先补齐本专题待核条件与规范状态，再确认联动');next=confirmDecision(next,contextFor(r.unit),L.role());}state.decisions=state.decisions.filter(x=>x.id!==r.id).concat(next);record(confirm?'负责人确认重难点':'修订重难点草稿');L.touchCard('c10');await save();dialog.close();render();emit();note(confirm?'已确认并接入扩初、PPT依据':'已保存判断草稿');}catch(e){dialog.querySelector('#kd-status').textContent=e.message;}};
  dialog.querySelector('#kd-draft').onclick=()=>commit(false);dialog.querySelector('#kd-confirm').onclick=()=>commit(true);dialog.showModal();
}
function renderMeasureDecisions(){let el=document.querySelector('#paper1 [data-decision-summary]');if(!el){el=document.createElement('section');el.dataset.decisionSummary='true';document.querySelector('#paper1').append(el);}const rows=state.decisions.filter(r=>r.status==='confirmed');el.innerHTML=rows.length?'<h1>项目重难点判断采用记录</h1>'+rows.map(r=>'<h2>'+esc(r.unit+' · '+(DECISION_TOPICS.find(t=>t[0]===r.topic)?.[2]||''))+'</h2><p>'+esc(r.conclusion)+(r.signature!==decisionSignature(contextFor(r.unit))?'【输入已变化，待复核】':'')+'</p><p>依据：'+esc((r.source_title||'已确认判断依据')+' · '+r.locator)+'</p>').join(''):'';}

function steelUnit(){return state.steel.units[activeUnit];}
function renderSteel(){
  const u=steelUnit(),t=materialSummary(u?.input);
  steelPanel.innerHTML='<div class="im-row"><h2>用钢量</h2><select id="im-steel-unit" aria-label="单体">'+options(units(),activeUnit)+'</select><button id="im-steel-export">导出 CSV</button></div>'+
    '<div class="im-grid">'+[['concrete','上部混凝土','.txt'],['rebar','楼层钢筋','.xlsx,.xls,.txt,.csv'],['foundation','基础混凝土','.txt']].map(([slot,label,accept])=>'<label class="im-topic">'+label+'<input type="file" data-material="'+slot+'" accept="'+accept+'" '+(slot==='rebar'?'multiple':'')+' '+(!canEdit('c5')?'disabled':'')+'><small>'+esc((u?.sources?.[slot]||[]).map(s=>s.name).join('、')||'尚未导入')+'</small></label>').join('')+'</div>'+
    '<label class="im-first-area">首层面积（m²）<input id="im-steel-first-area" type="number" min="0.01" step="any" value="'+esc(u?.input?.firstFloorArea??'')+'" placeholder="'+esc(t.firstFloorArea??'填写面积')+'" '+(!canEdit('c5')?'disabled':'')+'></label>'+
    '<div class="im-grid im-steel-metrics">'+[['楼层钢筋总用量（t）',t.tonnes,3],['钢筋单方量（kg/m²）',t.steelRate,2],['上部混凝土单方量（m³/m²）',t.concreteRate,3],['基础混凝土量（m³）',t.foundation,3],['基础混凝土单方量（m³/m²）',t.foundationRate,3]].map(([name,value,d])=>'<div class="im-topic"><small>'+name+'</small><span class="im-metric">'+fmt(value,d)+'</span></div>').join('')+'</div>'+
    t.warnings.map(w=>'<p class="im-warn">'+esc(w)+'</p>').join('')+renderMaterialTables(t);
  steelPanel.querySelector('#im-steel-unit').onchange=e=>{activeUnit=e.target.value;render();};
  steelPanel.querySelector('#im-steel-first-area').onchange=e=>action(async()=>{requireEdit('c5');const raw=e.target.value.trim();if(raw&&(!Number.isFinite(Number(raw))||Number(raw)<=0))throw Error('首层面积须大于0');const v=state.steel.units[activeUnit]||={input:{},sources:{},history:[]};v.input||={};v.history.push({event:'修改首层面积',previous:v.input.firstFloorArea??null,at:new Date().toISOString()});if(raw)v.input.firstFloorArea=Number(raw);else delete v.input.firstFloorArea;record('修改'+activeUnit+'首层面积');L.touchCard('c5');note('已保存');});
  steelPanel.querySelectorAll('[data-material]').forEach(input=>input.onchange=()=>action(async()=>{requireEdit('c5');busy=true;note('正在解析当前单体工程量…');const who=W.id,unit=activeUnit,slot=input.dataset.material;const results=[];for(const f of input.files){const parsed=await L.parseMaterial(slot,f);if(slot==='rebar'&&!parsed.length||slot==='concrete'&&!parsed.floors.length||slot==='foundation'&&!parsed.rows?.length)throw Error(f.name+' 未识别到有效工程量');const bytes=await f.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');results.push({parsed,source:{name:f.name,source_id:'MATERIAL-'+hash,at:new Date().toISOString()}});}if(who!==W.id)throw Error('项目已切换，请重新导入');const v=state.steel.units[unit]||={input:{},sources:{},history:[]};v.history.push({event:'导入'+slot,previous:clone(v.input),sources:clone(v.sources),at:new Date().toISOString()});if(slot==='rebar'){const merged=new Map((v.input.rebar||[]).map(r=>[r.floor,r]));for(const result of results)for(const f of result.parsed)merged.set(f.floor,f);v.input.rebar=[...merged.values()];}else v.input[slot==='concrete'?'up':'base']=results[0].parsed;v.sources[slot]=results.map(r=>r.source);record('导入'+unit+'材料用量');busy=false;L.touchCard('c5');note('已保存');}));
  steelPanel.querySelector('#im-steel-export').onclick=()=>{const rows=materialCsvRows(t,activeUnit);download((L.params().project_name||'项目')+'_'+activeUnit+'_材料用量.csv','\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');};
}

function renderOverview(){const local=Object.entries(state.steel.units).map(([name,u])=>({project:L.params().project_name,unit:name,review:u.review,current:u.review?.signature===steelSignature(u,I.parameters(name)),mode:W.mode}));const rows=[...local,...portfolio];overviewPanel.innerHTML='<h2>项目管理总览 · 已审核用量</h2><p>当前项目实时读取⑤审核记录；其他项目读取项目库中的已保存版本。范围不同的结果分行呈现。</p><button id="im-overview-refresh">刷新项目库审核结果</button><div class="im-scroll"><table><thead><tr><th>项目 / 单体</th><th>审核状态</th><th>统计范围</th><th>钢筋 t</th><th>kg/㎡</th><th>混凝土 m³</th><th>m³/㎡</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.project+' / '+r.unit)+(r.mode==='sample'?'（示例）':'')+'</td><td>'+(!r.review?'未审核':r.current?'已审核':'输入变化，待复核')+'</td><td>'+esc(r.review?.scope||'—')+'</td>'+[r.review?.totals.kg==null?null:r.review.totals.kg/1000,r.review?.totals.steelRate,r.review?.totals.volume,r.review?.totals.concreteRate].map(v=>'<td>'+fmt(r.current?v:null)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'+(!rows.length?'<p>项目库中尚无材料审核记录。</p>':'')+'<p class="im-muted">暂不将不同结构体系、阶段和计量范围合并排名；示例项目明确标识。</p>';
  overviewPanel.querySelector('#im-overview-refresh').onclick=()=>action(async()=>{busy=true;portfolio=[];const {projects}=await projectRequest('/');for(const p of projects.filter(p=>p.id!==W.id)){const archive=await projectRequest('/'+p.id),m=archive.records.modules?.data,main=archive.records.main?.data,intake=archive.records.intake?.data;for(const [name,u] of Object.entries(m?.steel?.units||{})){if(!u.review)continue;const {combinedParameters}=await import('./intake-core.js');const params=combinedParameters(intake||{facts:[]},name,main?.parameters||{});portfolio.push({project:p.name,unit:name,review:u.review,current:u.review.signature===steelSignature(u,params),mode:p.mode});}}busy=false;note('已读取项目库中的审核记录');});
}

function renderCleaning(){const imported=I.capture().history.filter(h=>h.bundle_id);cleaningPanel.innerHTML='<h2>接入已有资料清洗成果</h2><p>导入专项导出的 task2_bundle.json。原始值、冲突和旧确认记录一并保留；当前项目从候选开始复核。</p><input id="im-cleaning-file" type="file" accept=".json" '+(!canEdit('c1')?'disabled':'')+'>'+ (bundlePreview?'<div class="im-warn">待导入成果来自：'+esc(typeof bundlePreview.bundle.project==='object'?JSON.stringify(bundlePreview.bundle.project):bundlePreview.bundle.project||'未登记项目')+'<br>请先核对是否属于当前项目 '+esc(L.params().project_name)+'。</div><label>目标单体的原始名称<input id="im-cleaning-unit" value="'+esc(bundlePreview.bundle.target_building?.name||bundlePreview.bundle.target_building||'')+'"></label><label><input id="im-cleaning-confirm" type="checkbox"> 已核对该成果包属于当前项目；旧确认仅作参考</label><button id="im-cleaning-import">加入①候选清单</button>':'')+imported.map(h=>'<details><summary>'+esc(h.filename)+' · 迁移记录 / 未映射项 '+(h.unmapped?.length||0)+'</summary><p>复杂复合字段保持原义，不自动换算为单值。</p><pre>'+esc(JSON.stringify({unmapped:h.unmapped,issues:h.issues,previous_confirmations:h.previous_confirmations},null,2))+'</pre></details>').join('');
  cleaningPanel.querySelector('#im-cleaning-file').onchange=e=>action(async()=>{requireEdit('c1');const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024)throw Error('成果包超过8MB');const text=await file.text(),bundle=JSON.parse(text);convertCleaningBundle(bundle,'预检','preview');bundlePreview={bundle,name:file.name,id:'BUNDLE-'+fingerprint(text)};});
  const button=cleaningPanel.querySelector('#im-cleaning-import');if(button)button.onclick=()=>action(async()=>{requireEdit('c1');if(!cleaningPanel.querySelector('#im-cleaning-confirm').checked)throw Error('请先核对成果包所属项目');const converted=convertCleaningBundle(bundlePreview.bundle,cleaningPanel.querySelector('#im-cleaning-unit').value.trim(),bundlePreview.id);await I.importBundle(converted,{bundle_id:bundlePreview.id,filename:bundlePreview.name,at:new Date().toISOString()});bundlePreview=null;record('接入已有资料清洗成果');note('可映射字段已加入①候选；其余字段、问题和历史确认保留在迁移记录中');});
}
function renderPpt(){if(!pptPanel.querySelector('#im-ppt-open')){pptPanel.innerHTML='<h2>汇报 PPT · 当前项目成果</h2><p>已有16页编排、图片上传、AI润色和PPT下载已接入。单体参数、模型和已确认重难点由工作台单向提供。</p><div class="im-row"><button id="im-ppt-open" class="im-primary">打开当前项目 PPT 编辑器</button><button data-go="10">复核重难点</button><button data-go="2">核对扩初模型</button></div><div id="im-ppt-host"></div>';pptPanel.querySelector('#im-ppt-open').onclick=()=>openPpt();}}
function outputSnapshot(){const payload={type:'workbuddy:measure-snapshot',schema:2,project_id:W.id,parameter_version:W.parameterVersion,source_id:'workbuddy:unified-measures',params:L.params(),updated_at:new Date().toISOString(),context:{role:L.role(),stage:document.querySelector('#pstage-sel').value,canEdit:L.canEdit('c11')},units:units().map(name=>{const s=modelState(name);return {name,parameters:I.parameters(name),facts:I.evidence(name).facts,decisions:accepted(name),model:s?.model?.confirmed&&fingerprint(s.parameters)===fingerprint(I.parameters(name))?clone(s.model):null};})};payload.output_version=fingerprint([payload.params,payload.units]);return payload;}
function publishPpt(){if(loading||W.loading)return;const snapshot=outputSnapshot(),changed=lastOutputVersion&&lastOutputVersion!==snapshot.output_version;lastOutputVersion=snapshot.output_version;if(changed&&L.cardState('c11')>1)L.touchCard('c11');if(frameReady)frame?.contentWindow?.postMessage(snapshot,location.origin);}
async function openPpt(){if(loading||W.loading)return;await refreshExpansions();if(!frame){frame=document.createElement('iframe');frame.id='im-ppt-frame';frame.title='当前项目汇报PPT编辑器';frame.src='./design/parallel-tasks/06-ppt-report/prototype.html?embedded=1&project='+W.id;frame.onload=()=>{frameReady=true;publishPpt();};pptPanel.querySelector('#im-ppt-host').append(frame);}else publishPpt();}
async function refreshExpansions(){const who=W.id;const archive=await projectRequest('/'+who);if(who!==W.id)return;expansions=Object.fromEntries(Object.entries(archive.records).filter(([k,v])=>k.startsWith('expansion-')&&v?.data?.identity).map(([,v])=>[v.data.identity.unit,v.data]));}
function render(){if(loading)return;renderDecisions();renderSteel();renderOverview();renderCleaning();renderPpt();renderMeasureDecisions();}
function download(name,body,type){const a=document.createElement('a');a.download=name;a.href=URL.createObjectURL(new Blob([body],{type}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b)return;
  if(b.dataset.go)L.go(+b.dataset.go);
  if(b.dataset.decisionGroup){const group=DECISION_GROUPS.find(g=>g[0]===b.dataset.decisionGroup);if(group){activeDecisionGroup=group[0];activeDecisionTopic=group[3][0];renderDecisions();}return;}
  if(b.dataset.decisionTopic){activeDecisionTopic=b.dataset.decisionTopic;renderDecisions();return;}
  if(b.dataset.newDecision){const current=state.decisions.filter(r=>r.unit===activeUnit&&r.topic===b.dataset.newDecision).at(-1),guide=decisionGuide(contextFor(activeUnit),b.dataset.newDecision);editDecision(b.dataset.newDecision,current,!current&&guide?guide.draft:undefined);}
  if(b.dataset.editDecision){const r=state.decisions.find(r=>r.id===b.dataset.editDecision);editDecision(r.topic,r);}
});
let refreshing=false;
function changedInputs(){if(loading||W.loading)return;const e=E.capture();if(e)expansions[e.identity.unit]=e;if(!refreshing){refreshing=true;if(state.decisions.some(r=>r.status==='confirmed'&&r.signature!==decisionSignature(contextFor(r.unit)))&&L.cardState('c10')>1)L.touchCard('c10');refreshing=false;}renderDecisions();renderMeasureDecisions();renderSteel();publishPpt();window.dispatchEvent(new Event('workbuddy:decisions-changed'));}
window.addEventListener('workbuddy:measures-changed',changedInputs);window.addEventListener('workbuddy:intake-changed',changedInputs);window.addEventListener('workbuddy:expansion-changed',changedInputs);
window.addEventListener('workbuddy:permissions-changed',()=>{if(!loading){render();publishPpt();}});
window.addEventListener('workbuddy:stage-changed',e=>{if(e.detail===11)openPpt().catch(e=>note(e.message));if(e.detail===10)refreshExpansions().then(()=>renderDecisions()).catch(e=>note(e.message));if(e.detail===6)renderOverview();});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame?.contentWindow)return;if(e.data?.type==='workbuddy:request-measure-snapshot'){frameReady=true;publishPpt();}});
async function load({remoteOnly=false}={}){loading=true;clearTimeout(saveTimer);dialog.close();bundlePreview=null;frameReady=false;lastOutputVersion='';if(frame){frame.remove();frame=null;}store=undefined;state=fresh();activeUnit=PROJECT;activeDecisionGroup='seismic';activeDecisionTopic='intensity';portfolio=[];expansions={};try{const next=projectPart(W.id,'modules',note);const data=await next.load({remoteOnly});await refreshExpansions();state=data||fresh();store=next;}catch(e){loading=false;render();note('模块载入失败，请重载项目：'+e.message);throw e;}finally{loading=false;}render();emit();}
window.WorkbenchModules={openResearch:()=>{L.go(10);openResearch();},evidence:decisionEvidence,cardAction(id,act){if(id==='c11'&&act==='approve'&&!frame?.contentWindow?.WorkbenchPpt?.canSign()){note('请在⑪打开当前项目汇报并完成人工确认后再签发');return false;}if(id==='c10'&&act==='approve'&&(!state.decisions.length||state.decisions.some(r=>r.status!=='confirmed'||r.signature!==decisionSignature(contextFor(r.unit))))){note('重难点仍有草稿或输入变化，请先逐项确认');return false;}if(id==='c5'&&act==='approve'&&(!Object.keys(state.steel.units).length||Object.entries(state.steel.units).some(([n,u])=>!u.review||u.review.signature!==steelSignature(u,I.parameters(n))))){note('请在⑤逐单体审核用量后再签发');return false;}return true;}};
W.register('modules',{load,save:async()=>{if(frameReady){const bridge=frame?.contentWindow?.WorkbenchPpt;if(bridge?.busy())throw Error('PPT正在处理，请稍后保存或切换项目');await bridge?.flush();}await save();},capture:()=>clone(state),busy:()=>busy||Boolean(frameReady&&frame?.contentWindow?.WorkbenchPpt?.busy())});
await load();
