import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createResearchService,decisionResearchApi,validateResearch,parseSearch,officialUrl,fetchEvidence,searchEndpoint,evidencePassages} from '../../server/decision-research-api.mjs';
import {RESEARCH_TOPICS,researchContext,researchQueries,researchDraft} from '../../decision-research-method.js';

const quote='本测试条文仅用于接口验收，不作为实际工程设计依据。';
const searchResult={content:[{type:'web_search_tool_result',content:[{type:'web_search_result',url:'https://www.mohurd.gov.cn/test-notice.html',title:'测试官方条文'}]},{type:'text',citations:[{url:'https://www.mohurd.gov.cn/test-notice.html',cited_text:quote}]}]};
const body={consent:true,context:{unit:'A楼',parameters:{region:'江苏省南京市',project_name:'不应发送的项目名',intensity:'7'},facts:[{key:'use',value:'学校',unit:'A楼',status:'confirmed'},{key:'use',value:'医院',unit:'B楼',status:'confirmed'}]}};
function fixture(options={}){
  const calls=[];const deps={snapshot:{provinces:{江苏省:{aliases:['江苏','南京'],records:[]}}},registry:{sources:[]},readPage:async c=>({text:quote,url:c.url,kind:'官方网页摘录（未自动确认现行性）'}),fetch:async(url,request)=>{
    const sent=JSON.parse(request.body);calls.push({url,sent});if(url.endsWith('/messages'))return {ok:true,json:async()=>searchResult};
    const {evidence}=JSON.parse(sent.messages[1].content);return {ok:true,json:async()=>({model:'mock',choices:[{message:{content:JSON.stringify({items:Object.keys(RESEARCH_TOPICS).map(topic=>({topic,conclusion:'需依据当前项目条件复核',conditions:['用途学校'],checks:['核查正式版本'],missing:['场地资料待补'],citations:[{source_id:evidence[0].source_id,quote,locator:'测试条文第一段'}]}))})}}]})};
  },...options};return {deps,calls,run:createResearchService({DEEPSEEK_API_KEY:'test-placeholder'},deps)};
}
test('新地区三方面查询内嵌关键词，不带昆明结论或项目名',()=>{const q=researchQueries('江苏省南京市');assert.equal(q.length,3);assert.ok(q.every(x=>x.query.includes('site:gov.cn')));assert.doesNotMatch(JSON.stringify(q),/昆明|20%/);const c=researchContext(body.context);assert.equal(c.input.use,'学校');assert.doesNotMatch(JSON.stringify(c),/不应发送|医院/);});
test('只有实际工具结果可作搜索证据；伪URL和普通回答不算联网',()=>{assert.throws(()=>parseSearch({content:[{type:'text',text:'我查到了'}]}),/实际联网/);assert.equal(parseSearch(searchResult)[0].snippet,quote);for(const u of ['http://a.gov.cn','https://gov.cn.evil.test/x','https://user@a.gov.cn','https://127.0.0.1'])assert.equal(officialUrl(u),false);assert.equal(officialUrl('https://www.gov.cn/x'),true);});
test('自定义聊天网关不会将凭据自动发往DeepSeek官方',()=>{assert.throws(()=>searchEndpoint({DEEPSEEK_BASE_URL:'https://gateway.example/v1'}),/自定义AI网关/);assert.equal(searchEndpoint({DEEPSEEK_BASE_URL:'https://gateway.example/v1',DEEPSEEK_SEARCH_BASE_URL:'https://gateway.example/anthropic/v1'}),'https://gateway.example/anthropic/v1/messages');});
test('研判七专题带逐字引用，参数不改写；缓存复用且可强制刷新',async()=>{const {run,calls}=fixture(),original=JSON.stringify(body);const first=await run(body);assert.equal(first.items.length,7);assert.equal(JSON.stringify(body),original);assert.ok(first.items.every(x=>x.status==='draft'&&x.statement==='AI推断'));assert.equal(calls.filter(c=>c.url.endsWith('/messages')).length,3);assert.doesNotMatch(calls.at(-1).sent.messages[1].content,/不应发送的项目名|医院/);assert.match(calls.at(-1).sent.messages[0].content,/国家和地方触发条件独立/);const second=await run(body);assert.ok(second.trace.every(t=>t.cacheHit));assert.equal(calls.filter(c=>c.url.endsWith('/messages')).length,3);await run({...body,refresh:true});assert.equal(calls.filter(c=>c.url.endsWith('/messages')).length,6);const d=researchDraft(first,'grade');assert.match(d.evidence,/mohurd.gov.cn/);assert.ok(d.ai_research_version);});
test('缺密钥、无主动同意、地点不明确时均不调用模型',async()=>{const {run,calls}=fixture();await assert.rejects(run({...body,consent:false}),/主动启动/);await assert.rejects(run({...body,context:{parameters:{region:'经开区'}}}),/归属不明确/);await assert.rejects(createResearchService() (body),/尚未配置/);assert.equal(calls.length,0);});
test('引用必须属于实际证据且逐字存在，重复或缺失专题被拒绝',()=>{const sources=[{source_id:'S',text:quote,kind:'官方网页摘录（未自动确认现行性）'}],payload={items:Object.keys(RESEARCH_TOPICS).map(topic=>({topic,conclusion:'待核',citations:[{source_id:'S',quote,locator:'第一段'}]}))};assert.equal(validateResearch(payload,sources).length,7);payload.items[0].citations[0].quote='这是一段模型编造的文字，原文并不存在';assert.throws(()=>validateResearch(payload,sources),/原文校验/);payload.items[0].citations=[];assert.match(validateResearch(payload,sources)[0].conclusion,/证据不足/);payload.items.pop();assert.throws(()=>validateResearch(payload,sources),/缺失或重复/);});
test('摘要保持待核，禁止假装工程验算通过',()=>{const p={items:Object.keys(RESEARCH_TOPICS).map(topic=>({topic,conclusion:'待核',citations:[{source_id:'S',quote,locator:'检索摘录'}]}))};const s=[{source_id:'S',text:quote,kind:'检索摘要／正文待核'}];assert.match(validateResearch(p,s)[0].missing.join(),/补核官方全文/);p.items[0].conclusion='验算通过';assert.throws(()=>validateResearch(p,s),/通过断言/);});
test('模型选择片段编号，由服务端回填原文，伪造编号拒绝',()=>{const text=quote.repeat(80),passages=evidencePassages(text),sources=[{source_id:'S',text,passages,kind:'官方网页摘录（未自动确认现行性）'}];assert.equal(passages.map(p=>p.quote).join(''),text.slice(0,6500));const payload={items:Object.keys(RESEARCH_TOPICS).map(topic=>({topic,conclusion:'待核',citations:[{source_id:'S',passage_id:'P1',quote:'模型改写无效'}]}))};assert.equal(validateResearch(payload,sources)[0].citations[0].quote,passages[0].quote);payload.items[0].citations[0].passage_id='P999';assert.throws(()=>validateResearch(payload,sources),/不存在的原文片段/);});
test('存在缺项时，不把无法判断写成无强制要求或场地已确认',()=>{const source={source_id:'S',text:quote,kind:'官方网页摘录（未自动确认现行性）'},p={items:Object.keys(RESEARCH_TOPICS).map(topic=>({topic,conclusion:'当前无强制隔震要求，仅确认场地地震参数',missing:['用途未知'],citations:[{source_id:'S',quote,locator:'测试'}]}))};for(const r of validateResearch(p,[source])){assert.match(r.conclusion,/不能判定/);assert.doesNotMatch(r.conclusion,/无强制|仅确认/);}});
test('官方读取拒绝私网与跳转到非官方主机',async()=>{await assert.rejects(fetchEvidence({url:'https://example.gov.cn'},{lookupImpl:async()=>[{address:'127.0.0.1'}],fetchImpl:async()=>{throw Error('不应请求');}}),/不可公开/);await assert.rejects(fetchEvidence({url:'https://example.gov.cn'},{lookupImpl:async()=>[{address:'8.8.8.8'}],fetchImpl:async()=>({status:302,headers:new Headers({location:'https://evil.example/'})})}),/非允许/);});
test('无可用正文时不产生无来源的AI结论',async()=>{const {run,calls}=fixture({readPage:async()=>{throw Error('PDF');},fetch:async()=>({ok:true,json:async()=>({content:[{type:'text',text:'无工具结果'}]})})});await assert.rejects(run(body),/没有取得可引用/);assert.equal(calls.length,0);});
test('接口拒绝跨源、超长和缺少主动请求标记',async()=>{let handler;decisionResearchApi().configureServer({middlewares:{use:(_,h)=>handler=h}});async function call(headers,data){const req=Readable.from([Buffer.from(data)]);Object.assign(req,{method:'POST',headers:{host:'localhost:5197',...headers}});let result;await handler(req,{writeHead(status){result={status}},end(s){result.data=JSON.parse(s)}});return result;}
 assert.equal((await call({'x-workbench-request':'decision-research',origin:'https://evil.example'},'{}')).status,403);assert.equal((await call({},'{}')).status,403);assert.equal((await call({'x-workbench-request':'decision-research'},'x'.repeat(160001))).status,413);
});
