import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Readable} from 'node:stream';
import {regulationDiscoveryApi} from '../../server/regulation-discovery-api.mjs';
import {materialSummary,reviewSteel,steelSignature,confirmDecision,currentDecisions,convertCleaningBundle,decisionGuide} from '../../module-integration-core.js';

test('空项目用量为空，不把缺失转换为零或示例值',()=>{const t=materialSummary();assert.equal(t.kg,null);assert.equal(t.volume,null);assert.equal(t.steelRate,null);assert.equal(t.foundation,null);});
test('按面积加权，未知构件计入钢筋总量，汇总行不重复计入',()=>{const input={rebar:[{floor:1,area:100,rows:[{cat:'梁',total:1000},{cat:'未知构件',total:500},{cat:'合计',total:1500}]},{floor:2,area:200,rows:[{cat:'板',total:1000}]}]};const t=materialSummary(input);assert.equal(t.kg,2500);assert.equal(t.steelRate,2500/300);assert.equal(t.volume,null);});
test('资料面积或楼层范围冲突时阻止材料审核',()=>{const unit={input:{rebar:[{floor:1,area:100,rows:[{cat:'板',total:500}]}],up:{floors:[{floor:1,area:120,total:30,comp:[{name:'板',sum:30}]}]}},sources:{},scope:'地上1层'};assert.throws(()=>reviewSteel(unit,{},'m'),/面积不同/);unit.input.rebar[0].area=0;assert.equal(materialSummary(unit.input).steelRate,null);});
test('材料审核绑定原始数据、范围及项目参数；设计人员不能确认',()=>{const unit={input:{rebar:[{floor:1,area:100,rows:[{cat:'梁',total:500}]}]},sources:{},scope:'地上1层，不含基础'};assert.throws(()=>reviewSteel(unit,{},'d'),/负责人/);unit.review=reviewSteel(unit,{struct_sys:'框架'},'m');assert.equal(unit.review.signature,steelSignature(unit,{struct_sys:'框架'}));assert.notEqual(unit.review.signature,steelSignature(unit,{struct_sys:'剪力墙'}));assert.throws(()=>reviewSteel({input:{},scope:'空'}, {},'m'),/先导入/);});
test('只有带来源及定位的负责人决定可进入成果；变更及其他单体会失效',()=>{const context={parameters:{intensity:'7'}};const draft={unit:'A楼',conclusion:'测试结论',source_id:'TEST',locator:'测试记录1',scope:'A楼',evidence:'测试依据'};assert.throws(()=>confirmDecision(draft,context,'d'),/负责人/);assert.throws(()=>confirmDecision({...draft,locator:''},context,'m'),/补齐/);const accepted=confirmDecision(draft,context,'m');assert.equal(currentDecisions([accepted],'A楼',()=>context).length,1);assert.equal(currentDecisions([accepted],'B楼',()=>context).length,0);assert.equal(currentDecisions([accepted],'A楼',()=>({parameters:{intensity:'8'}})).length,0);});
test('保山判断只在地点与必要条件匹配时给出可编制建议',()=>{const context={parameters:{region:'云南省保山市隆阳区兰城街道',intensity:'8',pga:'0.20g',seismic_cat:'重点设防类',struct_sys:'框架—剪力墙'},facts:[{key:'bldg_use',value:'学校',quote:'新建政府投资公益性学校'},{key:'bldg_height_m',value:'48'},{key:'bldg_floors_above',value:'10'},{key:'bldg_bldg_total',value:'12000'}]};const intensity=decisionGuide(context,'intensity'),grade=decisionGuide(context,'grade'),green=decisionGuide(context,'green'),performance=decisionGuide(context,'performance');assert.equal(intensity.conclusion,'8度（0.20g）');assert.equal(intensity.ready,true);assert.equal(grade.conclusion,'框架一级，剪力墙一级');assert.equal(grade.ready,true);assert.equal(green.conclusion,'绿色建筑一星级及以上');assert.equal(green.ready,true);assert.equal(performance.ready,true);assert.match(performance.conclusion,/必须采用隔震或消能减震/);assert.equal(decisionGuide({...context,parameters:{...context.parameters,region:'天津市河东区'}},'intensity'),null);});
test('资料条件不全时只显示待补充，不生成可直接采用的建议',()=>{const context={parameters:{region:'云南省保山市隆阳区兰城街道',intensity:'8',pga:'0.20g'},facts:[{key:'bldg_use',value:'学校'}]};assert.equal(decisionGuide(context,'intensity').ready,true);assert.equal(decisionGuide(context,'grade').ready,false);assert.equal(decisionGuide(context,'green').ready,false);assert.equal(decisionGuide(context,'performance').ready,false);});
test('清洗成果保留来源冲突和旧确认，但重新从候选开始',()=>{const b={sources:[{source_id:'SRC',file_name:'测试建筑说明',domain:'建筑'}],candidates:[{candidate_id:'1',field_id:'building.name',normalized_value:'A楼',scope:'目标单体',source_id:'SRC',locator:'P1',evidence:'单体名称A楼',status:'已人工确认'},{candidate_id:'2',field_id:'building.height',normalized_value:'18.6',source_id:'SRC'}],confirmations:[{confirmed_value:'A楼'}],issues:[{issue:'冲突'}]};const a=convertCleaningBundle(b,'A楼','BUNDLE-A');assert.equal(a.facts[0].status,'candidate');assert.equal(a.facts[0].original_source_id,'SRC');assert.equal(a.unmapped.length,1);assert.equal(a.confirmations.length,1);assert.equal(a.issues.length,1);assert.equal(convertCleaningBundle(b,'B楼','BUNDLE-B').facts.length,0);});
test('正式入口载入模块集成，原型示例数据不作为模块初始状态',async()=>{const html=await readFile(new URL('../../workbuddy-integrated-studio.html',import.meta.url),'utf8');const js=await readFile(new URL('../../integrated-modules.js',import.meta.url),'utf8');assert.match(html,/src="\.\/integrated-modules\.js"/);assert.match(js,/decisions:\[\],steel:\{units:\{\}\}/);assert.doesNotMatch(js,/UNIT_A|REBAR_ROWS|CONCRETE_ROWS/);assert.doesNotMatch(js,/来源编号 source_id/);});
test('规范查询接入受控API，保留失败证据，不接受任意地区或跨源调用',async()=>{let handler,calls=0;const plugin=regulationDiscoveryApi(async input=>{calls++;return {query:input,records:[],sourceRuns:[{status:'failed',error:'测试超时'}]};});plugin.configureServer({middlewares:{use(path,fn){assert.equal(path,'/api/regulation-discovery');handler=fn;}}});async function call(body,origin='http://localhost:5191'){let code,result;const req=Readable.from([Buffer.from(JSON.stringify(body))]);req.method='POST';req.headers={host:'localhost:5191',origin,'x-workbench-request':'regulation-discovery'};await handler(req,{writeHead(c){code=c;},end(s){result=JSON.parse(s);}});return {code,result};}const query={province:'天津',asOf:'2026-10-01',keywords:'测试标准'};const ok=await call(query);assert.equal(ok.code,200);assert.equal(ok.result.sourceRuns[0].status,'failed');assert.equal((await call(query,'https://example.com')).code,403);assert.equal((await call({...query,province:'http://localhost/'})).code,400);assert.equal(calls,1);});
