import test from 'node:test';
import assert from 'node:assert/strict';
import {decisionGuide,decisionSignature,confirmDecision,currentDecisions} from '../../module-integration-core.js';
import {regionalInputs} from '../../regional-decision-guide.js';
const context=(overrides={})=>({unit:'A楼',parameters:{region:'云南昆明市经开区',intensity:'8',pga:'0.20g',seismic_cat:'重点设防类',struct_sys:'混凝土框架-剪力墙结构',site_class:'II 类',...overrides},facts:Object.entries({use:'学校教学楼',height_m:'48',floors_above:'10',bldg_total:'12000',project_nature:'新建',investment_type:'政府投资',building_kind:'政府投资公益性建筑',urban_scope:'是',super_highrise:'否',design_date:'2026-10-01',prefab_policy_2023:'是',regularity:'规则',seismic_scheme:'常规抗震'}).map(([key,value])=>({key,value,unit:'A楼',status:'confirmed',source_id:'TEST-CURRENT'}))});
const change=(c,key,value)=>{c.facts=c.facts.map(f=>f.key===key?{...f,value}:f);return c;};
test('昆明经开区七个专题按规则生成，完全不套保山固定结论',()=>{
 for(const topic of ['intensity','grade','green','prefab','performance','damping','isolation']){const g=decisionGuide(context(),topic);assert.ok(g);assert.ok(g.rows.length>=2);assert.ok(g.steps.length>=3);assert.equal(g.ready,true,topic+JSON.stringify(g.missing));assert.doesNotMatch(JSON.stringify(g),/保建发|隆阳|保山/);}
 assert.match(decisionGuide(context(),'prefab').conclusion,/20%/);assert.match(decisionGuide(context(),'grade').conclusion,/框架一级，抗震墙一级/);
});
test('只有地址时展示规则与具体缺项，不冒填烈度、学校或政府投资',()=>{for(const topic of ['intensity','grade','green','prefab','performance']){const g=decisionGuide({parameters:{region:'云南省昆明市经开区'}},topic);assert.equal(g.ready,false);assert.ok(g.rows.length);assert.equal(g.input.intensityValue,null);assert.equal(g.input.use,'');}});
test('候选与其他单体事实不参与判断，拒绝从项目名和原文顺带猜投资',()=>{const c=context();c.parameters.project_name='政府投资学校示例';c.facts=c.facts.map(f=>({...f,status:'candidate',quote:'政府投资学校'}));c.facts.push({key:'height_m',value:'80',status:'confirmed',unit:'B楼'});const input=regionalInputs(c);assert.equal(input.height,null);assert.equal(input.investment_type,'');assert.equal(decisionGuide(c,'green').ready,false);});
test('空值不转零，区间和约数不直接作为阈值事实',()=>{const c=context();change(c,'height_m','约48m');assert.equal(regionalInputs(c).height,null);change(c,'height_m','24～50m');assert.equal(regionalInputs(c).height,null);});
test('地区分流：昆明可省略云南，其他地区不误套昆明20%',()=>{assert.ok(decisionGuide(context({region:'昆明经济技术开发区'}),'prefab'));assert.equal(decisionGuide(context({region:'天津市经开区'}),'prefab'),null);assert.equal(decisionGuide(context({region:'上海市宝山区昆明路'}),'prefab'),null);assert.doesNotMatch(decisionGuide(context({region:'云南省昆明市东川区'}),'prefab').conclusion,/20%/);});
test('国家学校高烈度要求独立触发，不能被省级层数面积门槛排除',()=>{const c=context();change(c,'floors_above','2');change(c,'bldg_total','500');const g=decisionGuide(c,'performance');assert.equal(g.ready,true);assert.match(g.conclusion,/国家条款触发/);assert.match(g.rows[0].result,/不附加层数、面积/);});
test('云南7度学校三层1000㎡边界触发；缺项及既有建筑不冒充新建',()=>{const c=context({intensity:'7',pga:'0.10g'});change(c,'floors_above','3');change(c,'bldg_total','1000');assert.match(decisionGuide(c,'performance').conclusion,/云南条款触发/);change(c,'bldg_total','999');assert.equal(decisionGuide(c,'performance').ready,false);change(c,'project_nature','既有加固');assert.doesNotMatch(decisionGuide(c,'performance').conclusion,/条款触发/);});
test('投资、材料、许可条件改变后，装配式采用要求和比例分别变化',()=>{const c=context();change(c,'investment_type','社会投资');assert.match(decisionGuide(c,'prefab').conclusion,/鼓励/);c.parameters.struct_sys='钢结构';assert.doesNotMatch(decisionGuide(c,'prefab').conclusion,/≥20%/);change(c,'prefab_policy_2023','否');assert.equal(decisionGuide(c,'prefab').ready,false);});
test('普通查表范围、隔震例外、类别冲突和高度边界不直接就绪',()=>{for(const [key,value] of [['seismic_scheme','隔震'],['regularity','超限'],['height_m','50']]){const c=context();change(c,key,value);if(key==='height_m')change(c,key,'24');assert.equal(decisionGuide(c,'grade').ready,false);}
 const c=context({seismic_cat:'标准设防类'});assert.match(decisionGuide(c,'grade').missing.join(' '),/用途与设防类别冲突/);
 assert.equal(decisionGuide(context({intensity:'9',pga:'0.4g'}),'grade').ready,false);
 assert.equal(decisionGuide(context({pga:'0.1g'}),'grade').ready,false);
});
test('旧日期不套2026绿建办法；大型公共建筑按单体面积区分',()=>{const c=context();change(c,'design_date','2026-05-31');assert.equal(decisionGuide(c,'green').ready,false);change(c,'design_date','2026-06-01');change(c,'building_kind','一般公共建筑');change(c,'bldg_total','20000');assert.match(decisionGuide(c,'green').conclusion,/大型公共建筑一星/);change(c,'bldg_total','19999');assert.doesNotMatch(decisionGuide(c,'green').conclusion,/一星/);});
test('选中规范的状态变化阻止就绪并使旧确认失效；记录仍保留',()=>{const c=context();const g=decisionGuide(c,'prefab'),record=confirmDecision({...g.draft,unit:'A楼'},c,'m');assert.equal(currentDecisions([record],'A楼',()=>c).length,1);c.regulations=[{selected:true,source_id:'KM-YN-2021-42',title:'2021装配式通知',review:'confirmed',status:'repealed'}];assert.equal(decisionGuide(c,'prefab').ready,false);assert.equal(currentDecisions([record],'A楼',()=>c).length,0);assert.equal(record.status,'confirmed');});
test('项目地点、单体条件变化均改变签名；冲突确认资料不静默取第一个',()=>{const c=context(),before=decisionSignature(c);change(c,'investment_type','社会投资');assert.notEqual(before,decisionSignature(c));c.facts.push({key:'investment_type',value:'政府投资',unit:'A楼',status:'confirmed'});assert.equal(decisionGuide(c,'prefab').ready,false);assert.equal(regionalInputs(c).investment_type,'');});
test('绿色星级不以结构高度替代超高层建筑属性',()=>{const c=context();change(c,'height_m','110');assert.doesNotMatch(decisionGuide(c,'green').conclusion,/三星/);change(c,'super_highrise','是');assert.match(decisionGuide(c,'green').conclusion,/三星/);change(c,'super_highrise','');assert.equal(decisionGuide(c,'green').ready,false);});
