import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { mkdir } from 'node:fs/promises';
const require = createRequire(join(homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'));
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const context = await browser.newContext({ viewport: { width: 1600, height: 1100 }, acceptDownloads: true });
const main = await context.newPage();
const errors = [];
const output = join(process.cwd(), 'qa/ppt-report');
await mkdir(output, { recursive: true });
try {
  await main.goto('http://127.0.0.1:5190/workbuddy-integrated-studio.html');
  const popup = context.waitForEvent('page');
  await main.getByRole('button', { name: '汇报 PPT', exact: true }).click();
  const page = await popup;
  page.on('pageerror', (error) => errors.push(error.message));
  await page.waitForFunction(() => document.querySelector('#measure-link-btn')?.textContent === '技术措施已联动');
  await page.locator('[data-page="4"]').click();
  await page.locator('[data-param="intensity"]').waitFor();
  assert.equal(await page.locator('[data-param="intensity"]').getAttribute('contenteditable'), 'false');
  await main.evaluate(() => { setK('intensity', '7'); applyParams(); });
  await page.waitForFunction(() => document.querySelector('[data-param="intensity"]')?.textContent === '7 度');
  await page.locator('[data-page="11"]').click();
  await page.locator('.report-narrative').fill('节点尚待复核，重点说明连接构造。');
  await page.locator('#confirm-btn').click();
  await page.locator('[data-page="12"]').click();
  await page.locator('[data-page="11"]').click();
  assert.equal(await page.locator('.report-narrative').innerText(), '节点尚待复核，重点说明连接构造。');
  await main.evaluate(() => { setK('intensity', '8'); applyParams(); });
  await page.waitForFunction(() => document.querySelector('#confirm-btn')?.textContent === '人工确认');
  assert.equal(await page.locator('.report-narrative').innerText(), '节点尚待复核，重点说明连接构造。');
  await page.route('**/api/deepseek/chat', async (route) => {
    const body = route.request().postDataJSON();
    assert.equal(body.task, 'rewrite-ppt-report');
    await route.fulfill({ json: { content: JSON.stringify({ blocks: body.context.blocks.map((block) => ({ id: block.id, text: block.text + ' 请保留待确认标记。' })), warnings: [] }) } });
  });
  await page.locator('#rewrite-btn').click();
  await page.locator('#rewrite-apply:not([disabled])').waitFor();
  assert.equal(await page.locator('.report-narrative').innerText(), '节点尚待复核，重点说明连接构造。');
  await page.locator('#rewrite-apply').click();
  assert.match(await page.locator('.report-narrative').innerText(), /请保留待确认/);
  await page.locator('#rewrite-undo').click();
  assert.equal(await page.locator('.report-narrative').innerText(), '节点尚待复核，重点说明连接构造。');
  await page.unroute('**/api/deepseek/chat');
  await page.route('**/api/deepseek/chat', (route) => route.fulfill({ status: 503, json: { error: '模拟服务暂不可用' } }));
  await page.locator('#rewrite-btn').click();
  await page.waitForFunction(() => document.querySelector('#rewrite-status').textContent.includes('模拟服务暂不可用'));
  assert.equal(await page.locator('.report-narrative').innerText(), '节点尚待复核，重点说明连接构造。');
  assert.equal(await page.locator('#rewrite-apply').isDisabled(), true);
  await page.unroute('**/api/deepseek/chat');
  let pendingRoute;
  const requested = new Promise((resolve) => {
    page.route('**/api/deepseek/chat', (route) => { pendingRoute = route; resolve(); });
  });
  await page.locator('#rewrite-btn').click();
  await requested;
  await page.locator('.report-narrative').fill('节点尚待复核，重点说明连接构造。已补充人工说明。');
  const pendingBody = pendingRoute.request().postDataJSON();
  await pendingRoute.fulfill({ json: { content: JSON.stringify({ blocks: pendingBody.context.blocks, warnings: [] }) } });
  await page.waitForFunction(() => document.querySelector('#rewrite-status').textContent.includes('页面或参数已变化'));
  assert.equal(await page.locator('#rewrite-apply').isDisabled(), true);
  await page.locator('.report-narrative').fill('节点尚待复核，重点说明连接构造。');
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#measure-link-btn')?.textContent === '技术措施已联动');
  await page.locator('[data-page="11"]').click();
  assert.equal(await page.locator('.report-narrative').innerText(), '节点尚待复核，重点说明连接构造。');
  for (const index of [0, 3, 4, 6, 9, 10, 11, 12, 13, 14]) {
    await page.locator(`[data-page="${index}"]`).click();
    await page.locator('#slide-canvas').screenshot({ path: join(output, `slide-${index + 1}.png`) });
  }
  await page.screenshot({ path: join(output, 'editor.png'), fullPage: true });
  await page.locator('[data-page="2"]').click();
  const pixel = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jx1sAAAAASUVORK5CYII=', 'base64');
  await page.locator('[data-upload]').click();
  await page.locator('#image-input').setInputFiles({ name: 'regression.png', mimeType: 'image/png', buffer: pixel });
  await page.locator('.image-slot img').waitFor();
  const downloaded = page.waitForEvent('download');
  await page.locator('#generate-btn').click();
  const download = await downloaded;
  await download.saveAs(join(output, 'report-regression.pptx'));
  await page.locator('#generate-btn:not([disabled])').waitFor();
  await main.evaluate(() => { setK('project_name', '参数联动回归测试项目'); applyParams(); });
  await page.waitForFunction(() => document.querySelector('#project-name')?.value === '参数联动回归测试项目');
  await page.locator('[data-page="11"]').click();
  assert.equal(await page.locator('.report-narrative').innerText(), '[待补充本页汇报要点]');
  assert.deepEqual(errors, []);
  console.log('PASS: main entry, parameter linkage, read-only cells, edit retention, review invalidation, AI preview/apply/undo, reload, project isolation, actual PPTX download.');
} finally { await browser.close(); }
